language: node_js
node_js:
- 8
services:
- docker
before_install:
- bash scripts/commands.sh
- bash scripts/commands.sh build-image
script:
- bash scripts/commands.sh build-demos
- du --max-depth=1 --human-readable scripts/server
- du --max-depth=2 --human-readable --all scripts/server | grep '.js'
