sudo: required

language: haxe

services:
  - docker

before_install:
  - bash commands.sh
  - bash commands.sh build-image

script:
  - bash commands.sh build-demos
  - du --max-depth=1 --human-readable *
